basetheme_default <- function() {
  palette <- c("black", "red", "green3", "blue", "cyan", "magenta", "yellow", "gray")
  list(fg           = "black",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "transparent",
       bty          = "o",
       cex          = 1,
       cex.axis     = 1,
       cex.lab      = 1,
       cex.main     = 1.2,
       cex.sub      = 1,
       col          = "black",
       col.axis     = "black",
       col.lab      = "black",
       col.main     = "black",
       col.sub      = "black",
       family       = "",
       font         = 1,
       font.axis    = 1,
       font.lab     = 1,
       font.main    = 2,
       font.sub     = 1,
       lab          = c(5, 5, 7),
       las          = 0,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = "solid",
       lwd          = 1,
       mgp          = c(3, 1, 0),
       pch          = 1,
       tck          = NA,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = NA,
       rect.density = numeric(),
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}


basetheme_minimal <- function() {
  light   <- c("#5DDAD1", "#80E835", "#FCF705", "#FFB953", "#DA9A7D", "#F5A2DC","#CD93E9", "#AF8548", "#737373", "#F6F5F3")
  medium  <- c("#5DA5DA", "#60BD68", "#FCE205", "#FAA43A", "#F15854", "#F17CB0","#B276B2", "#795C32", "#4D4D4D", "#D6CFC7")
  dark    <- c("#335AD1", "#3D9344", "#B2A002", "#F36106", "#712116", "#C01460","#6E4F8D", "#554123", "#272727", "#B6A99B")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "black",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "white",
       bty          = "n",
       cex          = 1,
       cex.axis     = 0.8,
       cex.lab      = 1,
       cex.main     = 1.2,
       cex.sub      = 1,
       col          = "black",
       col.axis     = "black",
       col.lab      = "black",
       col.main     = "black",
       col.sub      = "black",
       family       = "serif",
       font         = 1,
       font.axis    = 1,
       font.lab     = 1,
       font.main    = 2,
       font.sub     = 2,
       lab          = c(4,4,7),
       las          = 1,
       lend         = 0,
       ljoin        = 0,
       lmitre       = 10,
       lty          = 1,
       lwd          = 1,
       mgp          = c(2.5,0.2,0),
       pch          = 20,
       tck          = 0,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     =  NA,
       rect.density =  numeric(),
       rect.angle   =  45,
       rect.lwd     =  1,
       rect.lty     =  1,
       rect.border  =  NA,
       palette      =  palette
       )
}


basetheme_void <- function() {
  light   <- c("#5DDAD1", "#80E835", "#FCF705", "#FFB953", "#DA9A7D", "#F5A2DC","#CD93E9", "#AF8548", "#737373", "#F6F5F3")
  medium  <- c("#5DA5DA", "#60BD68", "#FCE205", "#FAA43A", "#F15854", "#F17CB0","#B276B2", "#795C32", "#4D4D4D", "#D6CFC7")
  dark    <- c("#335AD1", "#3D9344", "#B2A002", "#F36106", "#712116", "#C01460","#6E4F8D", "#554123", "#272727", "#B6A99B")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "black",
       adj          = 0.5,
       ann          = FALSE,
       bg           = "white",
       bty          = "n",
       cex          = 1,
       cex.axis     = 1.1,
       cex.lab      = 1.1,
       cex.main     = 1.5,
       cex.sub      = 1,
       col          = "black",
       col.axis     = "black",
       col.lab      = "black",
       col.main     = "black",
       col.sub      = "black",
       family       = "",
       font         = 1,
       font.axis    = 1,
       font.lab     = 1,
       font.main    = 2,
       font.sub     = 2,
       lab          = c(5,5,7),
       las          = 1,
       lend         = 0,
       ljoin        = 0,
       lmitre       = 10,
       lty          = 1,
       lwd          = 2,
       mgp          = c(3,0.5,0),
       pch          = 19,
       tck          = 0,
       xaxs         = "r",
       xaxt         = "n",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "n",
       rect.col     =  NA,
       rect.density =  numeric(),
       rect.angle   =  45,
       rect.lwd     =  1,
       rect.lty     =  1,
       rect.border  =  NA,
       palette      =  palette
       )
}


basetheme_brutal <- function() {
  light  <- c("#90C4C6", "#58ca5d", "#FDEB38", "#F4A539", "#DD5C5E", "#EE63CD", "#C065EF", "#B7793C", "#505A70", "#E8EBEE")
  medium <- c("#5E81AC", "#8FA87A", "#E7D202", "#F49538", "#BF616A", "#D070B9", "#8770D0", "#7D5329", "#303643", "#BCC3CE")
  dark   <- c("#405C7D", "#548155", "#B5A401", "#BC620B", "#A5434C", "#A4368A", "#793CB7", "#573A1C", "#101216", "#909BAE")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "#3b4252",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "white",
       bty          = "o",
       cex          = 1,
       cex.axis     = 1.2,
       cex.lab      = 1.5,
       cex.main     = 2,
       cex.sub      = 1.5,
       col          = "#3b4252",
       col.axis     = "#3b4252",
       col.lab      = "#3b4252",
       col.main     = "#3b4252",
       col.sub      = "#3b4252",
       family       = "mono",
       font         = 2,
       font.axis    = 1,
       font.lab     = 2,
       font.main    = 2,
       font.sub     = 2,
       lab          = c(4,4,7),
       las          = 1,
       lend         = 0,
       ljoin        = 0,
       lmitre       = 10,
       lty          = 1,
       lwd          = 4,
       mgp          = c(2.5,0.25,0),
       pch          = 15,
       tck          = 0,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     =  NA,
       rect.density =  numeric(),
       rect.angle   =  45,
       rect.lwd     =  4,
       rect.lty     =  1,
       rect.border  =  NA,
       palette      =  palette
       )
}


basetheme_clean <- function() {
  light   <- c("#5DDAD1", "#80E835", "#FCF705", "#FFB953", "#DA9A7D", "#F5A2DC","#CD93E9", "#AF8548", "#737373", "#F6F5F3")
  medium  <- c("#5DA5DA", "#60BD68", "#FCE205", "#FAA43A", "#F15854", "#F17CB0","#B276B2", "#795C32", "#4D4D4D", "#D6CFC7")
  dark    <- c("#335AD1", "#3D9344", "#B2A002", "#F36106", "#712116", "#C01460","#6E4F8D", "#554123", "#272727", "#B6A99B")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "black",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "white",
       bty          = "o",
       cex          = 1,
       cex.axis     = 0.7,
       cex.lab      = 0.8,
       cex.main     = 1,
       cex.sub      = 0.8,
       col          = "black",
       col.axis     = "black",
       col.lab      = "black",
       col.main     = "black",
       col.sub      = "black",
       family       = "",
       font         = 1,
       font.axis    = 1,
       font.lab     = 1,
       font.main    = 2,
       font.sub     = 3,
       lab          = c(5, 5, 7),
       las          = 1,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = "solid",
       lwd          = 1,
       mgp          = c(2, 0.5, 0),
       pch          = 20,
       tck          = -0.01,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = NA,
       rect.density = numeric(),
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}


basetheme_ink <- function() {
  light  <- c("#00FFFF", "#00D800", "#FEFF62", "#FFCC00", "#FF8080", "#F67EBF", "#D398F8", "#CE661C", "#A3AEBA", "#FFFFFF")
  medium <- c("#0000FF", "#008B00", "#ECC700", "#FF8C00", "#FF0000", "#EE1289", "#A020F0", "#8B4513", "#778899", "#FAEBD7")
  dark   <- c("#0000B3", "#003F00", "#B39700", "#B36200", "#B30000", "#A70C60", "#560987", "#5E2F0D", "#546270", "#EAE9E7")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "blue",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "navajowhite",
       bty          = "o",
       cex          = 0.8,
       cex.axis     = 1,
       cex.lab      = 1,
       cex.main     = 1.5,
       cex.sub      = 1,
       col          = "blue",
       col.axis     = "blue",
       col.lab      = "blue",
       col.main     = "blue",
       col.sub      = "blue",
       family       = "",
       font         = 3,
       font.axis    = 3,
       font.lab     = 4,
       font.main    = 2,
       font.sub     = 3,
       lab          = c(5, 5, 7),
       las          = 1,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = "dotted",
       lwd          = 2,
       mgp          = c(2, 0.5, 0),
       pch          = 4,
       tck          = -0.01,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = "gray80",
       rect.density = 10,
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}


basetheme_dark <- function() {
  light   <- c("#00FAF1", "#46FE17", "#FFF200", "#EF820D", "#FA8072", "#F987C5", "#9966CB", "#BD9B75", "#FFFFFF", "#48494B")
  medium  <- c("#3870C2", "#66C84D", "#F2D63B", "#FC6600", "#ED2939", "#FC0FCD", "#8F00FF", "#8A6842", "#BAC1BF", "#222021")
  dark    <- c("#00008B", "#043927", "#AE8319", "#964000", "#800000", "#B5338A", "#702963", "#492000", "#444C49", "#050505")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "#7E848C",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "#2E3947",
       bty          = "n",
       cex          = 0.8,
       cex.axis     = 1,
       cex.lab      = 1,
       cex.main     = 1.5,
       cex.sub      = 1,
       col          = "#BEBEBE",
       col.axis     = "#7E848C",
       col.lab      = "#BEBEBE",
       col.main     = "#EFF0F2",
       col.sub      = "#737D89",
       family       = "",
       font         = 1,
       font.axis    = 1,
       font.lab     = 2,
       font.main    = 2,
       font.sub     = 3,
       lab          = c(5, 5, 7),
       las          = 1,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = 1,
       lwd          = 1,
       mgp          = c(3, 0.7, 0),
       pch          = 19,
       tck          = -0.01,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = NA,
       rect.density = numeric(),
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}

basetheme_deepblue <- function() {
  light  <- c("#3AD7E4", "#3AE49C", "#D6F18C", "#ECB542", "#DC7F61", "#F49AAF", "#C955EC", "#AF8548", "#DFE0DE", "#767676")
  medium <- c("#3A82E4", "#42BA90", "#BEE948", "#C38A13", "#C4512C", "#EC5578", "#9041BA", "#795C32", "#B9BBB6", "#363636")
  dark   <- c("#195DB8", "#2E8264", "#9CCC19", "#AC7A11", "#9B4023", "#C5166B", "#7016C5", "#554123", "#93968E", "#101010")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "#CCCCCC",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "#002E49",
       bty          = "l",
       cex          = 1,
       cex.axis     = 0.8,
       cex.lab      = 0.8,
       cex.main     = 1,
       cex.sub      = 0.8,
       col          = "#BEBEBE",
       col.axis     = "#BEBEBE",
       col.lab      = "#FFFFFF",
       col.main     = "#FFFFFF",
       col.sub      = "#326D87",
       family       = "",
       font         = 1,
       font.axis    = 1,
       font.lab     = 2,
       font.main    = 2,
       font.sub     = 3,
       lab          = c(5, 5, 7),
       las          = 1,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = 1,
       lwd          = 2,
       mgp          = c(3, 0.7, 0),
       pch          = 21,
       tck          = -0.015,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = NA,
       rect.density = numeric(),
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}

basetheme_royal <- function() {
  light  <- c("#11BBAC", "#62D056", "#F9FCA8", "#F3AB7F", "#CF6970", "#F184D4",  "#AE83D1", "#B18C69", "#FFFFFF", "#7B7B7B")
  medium <- c("#1175BB", "#34952A", "#FADA5E", "#EE6450", "#B33941", "#E93FBC",  "#7D40AE", "#664C35", "#E5DDCE", "#363636")
  dark   <- c("#0D588C", "#1F5919", "#BA9506", "#DC2F15", "#79272C", "#AE1485",  "#552B76", "#443324", "#B3AB9A", "#0f0f0f")
  palette <- expandPalette(light, medium, dark)
  list(fg           = "#DACEC4",
       adj          = 0.5,
       ann          = TRUE,
       bg           = "#2D2D3B",
       bty          = "o",
       cex          = 1,
       cex.axis     = 0.8,
       cex.lab      = 0.8,
       cex.main     = 1.2,
       cex.sub      = 0.8,
       col          = "#DACEC4",
       col.axis     = "#DACEC4",
       col.lab      = "#FFFFFF",
       col.main     = "#FFFFFF",
       col.sub      = "#DACEC4",
       family       = "serif",
       font         = 1,
       font.axis    = 1,
       font.lab     = 2,
       font.main    = 2,
       font.sub     = 3,
       lab          = c(5, 5, 7),
       las          = 1,
       lend         = "round",
       ljoin        = "round",
       lmitre       = 10,
       lty          = 1,
       lwd          = 1.2,
       mgp          = c(3, 0.7, 0),
       pch          = 21,
       tck          = -0.015,
       xaxs         = "r",
       xaxt         = "s",
       xpd          = FALSE,
       yaxs         = "r",
       yaxt         = "s",
       rect.col     = NA,
       rect.density = numeric(),
       rect.angle   = 45,
       rect.lwd     = 1,
       rect.lty     = 1,
       rect.border  = NA,
       palette      = palette
       )
}

list_themes <- function() {
  c(brutal   = basetheme_brutal,
    clean    = basetheme_clean,
    default  = basetheme_default,
    ink      = basetheme_ink,
    minimal  = basetheme_minimal,
    dark     = basetheme_dark,
    deepblue = basetheme_deepblue,
    royal    = basetheme_royal,
    void     = basetheme_void
    )
}
